Fetch tag data from gitlab and github
jboss-set/build-trigger pull request #35
Opened 2024-09-18 14:49 UTC by petrberan

2024-09-19 08:52 UTC, xjusko approved these changes
LGTM.

2024-09-19 13:37 UTC, khermano requested changes

2024-09-19 14:22 UTC, petrberan commented on src/main/java/org/jboss/set/BuildTriggerResource.java
> +            return Response.status(400, "List of streams is empty").build();
Don't think so. The 422 is to be returned when the content of the input contains invalid values. If there are no values, the BuildInfo is invalid and 400 should be returned. 

Digging a bit deeper, it should probably be split. The `triggerBuild` method should check if the `buildInfo.streams` exist. If not, 400 should be returned. If yes, even if empty, it should be passed to the following method that checks the content of the list. 

In that case the exception needs a better handling on the following method.

2024-09-19 14:31 UTC, petrberan commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +    private final static String COMMIT = "commit";
Matter of taste really. Besides better readability the constant ensures that the variable will be initialized only once for each instance of the class. When using variable, it's initialized for every instance. And since this class should be initialized only once, it's really just a case of whichever we prefer

2024-09-19 14:52 UTC, petrberan commented on src/main/java/org/jboss/set/BuildTriggerResource.java
> +    @Path("/get")
Sounds good to me. If you have a better name for the BuildInfoFromGitConstructor class, I'm all ears

2024-09-19 14:54 UTC, petrberan commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +        try (Client client = ClientBuilder.newClient()) {
Honestly thought I was using the Quarkus REST Client, my mistake there

2024-09-19 14:54 UTC, petrberan commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +                buildInfo.commitSha = commitSHA;
A relic of times long gone. Good point

2024-09-19 15:11 UTC, khermano commented on src/main/java/org/jboss/set/BuildTriggerResource.java
> +    @Path("/get")
What about BuildInfoFetcher?

2024-09-19 15:16 UTC, khermano commented on src/main/java/org/jboss/set/BuildTriggerResource.java
> +            return Response.status(400, "List of streams is empty").build();
I forgot that streams are not fetched from the git and must be filled by the user. You're right. And yes, splitting it sounds good to me.

2024-09-25 13:15 UTC, petrberan commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +                buildInfo.commitSha = commitSHA;
Actually, looking at again this saves a one single call as the variable is used both in logger and setting the buildInfo

2024-09-25 13:16 UTC, petrberan commented on src/main/java/org/jboss/set/BuildTriggerResource.java
> +    @Path("/get")
It doesn't fetch BuildInfo though, it creates a BuildInfo from fetched data :)

2024-09-25 13:17 UTC, petrberan commented on pom.xml
> +      <artifactId>httpclient</artifactId>
In the end I decided to leave the htttpclient as is. Migrating from httpclient to httpclient5 was pretty tedious, so I'll leave this as is and create an issue afterwards

2024-09-26 09:30 UTC, khermano commented on pom.xml
> +      <artifactId>httpclient</artifactId>
Ok, understood.

2024-09-26 09:30 UTC, khermano commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +        if (tagUrl.getHost().equals("gitlab.cee.redhat.com")) {
Did you have a chance to look at this?

2024-09-26 09:30 UTC, khermano commented on src/main/java/org/jboss/set/BuildTriggerResource.java
> +    @Path("/get")
What about GitBuildInfoCreator, or GitBuildInfoAssembler/ BuildInfoAssembler?

2024-09-26 09:39 UTC, khermano requested changes

2024-09-26 09:39 UTC, khermano commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +                buildInfo.commitSha = commitSHA;
I believe we could do something like this, so we do not create unnecessary strings. What do you think? :

                BuildInfo buildInfo = new BuildInfo();
                buildInfo.tag = tagUrl.toString();
                buildInfo.commitSha = tagJson.get(OBJECT).get(SHA).textValue();
                buildInfo.gitRepo = tagUrl.getProtocol() + "://" +  tagUrl.getHost() + "/" + codeSpace + "/" + repository;
                buildInfo.projectVersion = tagJson.get(TAG).textValue();

                logger.infof("Build created with following parameters - sha: %s, version: %s, link: %s", buildInfo.commitSha, buildInfo.projectVersion, buildInfo.tag);
                return buildInfo;

2024-09-26 09:39 UTC, khermano commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +            try (CloseableHttpResponse response = httpClient.execute(request)) {
In the future we should also look at this (most probably together with the upgrade of the artifact above) because I believe there is a better way in Quarkus how to do this. But for the sake of the time I understand we are not doing it now.

2024-09-26 13:02 UTC, petrberan commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +                buildInfo.commitSha = commitSHA;
Fixed

2024-09-26 13:04 UTC, petrberan commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +        if (tagUrl.getHost().equals("gitlab.cee.redhat.com")) {
Switch is overkill for two instances IMHO. The "gitlab.cee.redhat.com" is checking for a hit, the "github." and "gitlab." are checking whether the string contains the host

2024-09-26 13:15 UTC, petrberan commented on src/main/java/org/jboss/set/BuildTriggerResource.java
> +    @Path("/get")
I like the GitBuildInfoAssembler, we'll use this one

2024-09-26 14:50 UTC, khermano commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +        if (tagUrl.getHost().equals("gitlab.cee.redhat.com")) {
It could be good in the future when there is more, but since we now have only two instances, it is unnecessary. Thanks

2024-09-26 14:54 UTC, khermano commented on src/main/java/org/jboss/set/BuildInfoFromGitConstructor.java
> +            try (CloseableHttpResponse response = httpClient.execute(request)) {
I see...and I understand your concern. I will leave that up to you then but in the meantime, I am giving you good to go.

2024-09-26 14:55 UTC, khermano approved these changes
Thank you @petrberan very very much!!!

2024-09-27 07:11 UTC, merged