Handle tag/commit type case in github
jboss-set/build-trigger pull request #41
Opened 2024-09-30 13:25 UTC by petrberan

Resolves #40

2024-10-01 08:53 UTC, khermano requested changes
Looks good, but we should also take care about the 404. When the tag format is valid but tag does not exist (e.g.: https://github.com/wildfly/wildfly-arquillian/releases/tag/8.0.1.Final).

2024-10-01 14:22 UTC, petrberan commented
Added exception handling @khermano

2024-10-03 13:03 UTC, petrberan commented on src/main/java/org/jboss/set/exception/GitRestClientExceptionMapper.java
> +public class GitRestClientExceptionMapper implements ExceptionMapper<ClientWebApplicationException> {
Agree, this is was just the fastest solution.

Feel free to open an issue

2024-10-03 13:29 UTC, petrberan commented
Changed some of the lines there.

I'll leave it at this state, the response with some user-friendly lines are needed across the project and since this is just a warning in the logger we might as well leave it for the next beta release.

Can you create an issue to provide more robust Responses with some valid messages @khermano ?

2024-10-03 14:03 UTC, khermano approved these changes
LGTM, I will create mentioned issues. Thanks @petrberan

2024-10-03 14:25 UTC, merged