add info footer containing link to the GitHub repo
jboss-set/build-trigger pull request #51
Opened 2024-10-10 12:12 UTC by xjusko

resolves #48

2024-10-10 14:09 UTC, petrberan approved these changes
That was premature :)

2024-10-10 14:12 UTC, petrberan requested changes
^

2024-10-11 08:33 UTC, khermano approved these changes

2024-10-11 11:50 UTC, petrberan approved these changes
LGTM

2024-10-11 11:50 UTC, merged