add backend checks for BuildInfo
jboss-set/build-trigger pull request #58
Opened 2024-10-17 14:04 UTC by xjusko

resolves #56

2024-10-23 09:19 UTC, petrberan commented on src/test/java/org/jboss/set/model/json/BuildInfoTest.java
> +    private static final List<String> VALID_STREAMS = List.of("EAP_7_3_X");
This should probably be replaced with `List.of(Stream.EAP_7_3_X.frontEnd)`

2024-10-23 09:30 UTC, petrberan commented on src/test/java/org/jboss/set/model/json/BuildInfoTest.java
> +    private final Validator validator;
I'd prefere non-test methods (and classes) to be after the tests

2024-10-23 14:59 UTC, khermano requested changes

2024-10-23 14:59 UTC, khermano commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +@JsonDeserialize(builder = BuildInfo.Builder.class)
Why do we need to use a builder? Constraints like NotBlank, Pattern, and so on should be enough or not?
Trimming can be simply done through a set method (it is generated by Quarkus but we might override it simply by adding it here if needed) e.g.:
```
public void setTag(@NotNull String tag) {
        this.tag = tag.trim();
    }
```

Is there any other reason I am missing here?

2024-10-23 14:59 UTC, khermano commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +    @Size(max = 5, message = "The maximum number of streams allowed is 5.")
Minimal size = 1 should be also defined

2024-10-23 14:59 UTC, khermano commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +    private final String tag;
Also, please remove public access modifiers and leave it as package-private if no specific reason to do it otherwise. These were left there by mistake.

2024-10-24 08:03 UTC, xjusko commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +@JsonDeserialize(builder = BuildInfo.Builder.class)
I decided to use Builder and not setters because I think once BuildInfo is created, it is not supposed to be changed or edited. Or why do you think setters would be better?
Field annotations are only validated when we pass the BuildInfo through the @Valid annotation, which does not happen in GitBuildInfoAssembler, for example.

2024-10-24 08:04 UTC, xjusko commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +    private final String tag;
I am not sure what you mean by this, I replaced public with private modifiers.

2024-10-24 13:15 UTC, khermano commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +@JsonDeserialize(builder = BuildInfo.Builder.class)
You are right, I forgot about creation in GitBuildInfoAssembler for a sec.

2024-10-24 13:16 UTC, khermano commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +    private final String tag;
That was for case we would not use Builder, so you can ignore it. :)

2024-10-24 14:10 UTC, khermano requested changes
For now, I would say only the minimal size of streams needs to be taken care of. In UI we can't create a Build request if at least one stream is not chosen.

2024-10-29 14:41 UTC, petrberan commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +    @Size(max = 5, message = "The maximum number of streams allowed is 5.")
"null elements are considered valid" so yes, min size should be there as well

2024-10-31 10:04 UTC, khermano requested changes

2024-10-31 10:04 UTC, khermano commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +    @Size(min = 1, max = 5, message = "The maximum number of streams allowed is 5.")
Message should be also changed. E.g.: "The number of streams must be between 1 and 5."

2024-10-31 10:04 UTC, khermano commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +            if (streams != null && streams.size() > Stream.values().length) {
Message and min size need to be update also here

2024-10-31 10:15 UTC, xjusko commented
thanks @khermano , it should be fixed now

2024-10-31 10:47 UTC, khermano requested changes

2024-10-31 10:47 UTC, khermano commented on src/main/java/org/jboss/set/model/json/BuildInfo.java
> +                throw new IllegalArgumentException(String.format("The maximum number of streams allowed is %d.", Stream.values().length));
Please also update here message to "The number of streams must be between 1 and 5."

2024-11-01 14:32 UTC, merged