Create Component Upgrade issue when build is triggered
jboss-set/build-trigger pull request #78
Opened 2024-11-07 13:06 UTC by petrberan

resolves #24

2024-11-07 13:59 UTC, xjusko requested changes

2024-11-07 13:59 UTC, xjusko commented on src/main/java/org/jboss/set/jira/JiraService.java
> +            System.out.println("Issue sent to Jira successfully.");
I think we should use the Logger instead of the System print.

2024-11-07 13:59 UTC, xjusko commented on src/main/java/org/jboss/set/jira/JiraService.java
> +            fields.put("description", "This is an automated issue created by Build Trigger on behalf of [~" + user + "]\n\n" +
If the user is null, there should be a different description. Because currently, it would display null in the text I think.

2024-11-07 13:59 UTC, xjusko commented on src/main/java/org/jboss/set/BuildTrigger.java
> +            ObjectNode issuesBatch = jiraService.createIssuesBatch(buildInfo, jiraService.getUser(email));
I would pass only the email into the `createIssuesBatch` method and call `getUser` there. Therefore, you can make the getUser private, which would make the code cleaner.

2024-11-07 14:49 UTC, petrberan commented on src/main/java/org/jboss/set/jira/JiraService.java
> +    private String authorizationHeader = "Bearer " + jiraKey;
Also @khermano you're more experienced when it comes to Quarkus, will this work?

2024-11-08 10:58 UTC, khermano requested changes

2024-11-08 10:58 UTC, khermano commented on src/main/java/org/jboss/set/BuildTrigger.java
> +            jiraService.sendIssuesBatch(issuesBatch);
We should keep this functionality inside the JiraService if possible. It is a bit confusing going back and forth so issuesBatch should be created inside the JiraService. (e.g.: jiraService.sendIssuesBatch(buildInfo, email))

2024-11-08 10:58 UTC, khermano commented on src/main/java/org/jboss/set/jira/JiraService.java
> +            else {
just a small thing but this should be one row up -> "} else {"

2024-11-08 10:58 UTC, khermano commented on src/main/java/org/jboss/set/jira/JiraService.java
> +                fields.put("description", "This is an automated issue created by Build Trigger\n\n" +
Are we sure we want to be able to create the issue without assignee? 
Also how is the reporter of the issue set? Who is it now? Is the issue created in dev mode? There should be some message like "Component upgrade issue not send in dev mode" or because of email not provided, because right now in dev mode I was able to send test UMB message, email was not send because there was no email provided (I got warning about that in console) and I am not sure if the issue was created or was not, how should I find it?

2024-11-08 10:58 UTC, khermano commented on src/main/java/org/jboss/set/jira/JiraService.java
> +                fields.put("description", "This is an automated issue created by Build Trigger\n\n" +
Also I think it would be great to provide issues or maybe even link to them if they were successfully created.

2024-11-08 11:02 UTC, khermano requested changes

2024-11-08 11:02 UTC, khermano commented on src/main/java/org/jboss/set/jira/JiraService.java
> +                    "cc [~eleandro]/[~dkreling]\n\n";
I don't think this should be a public information. We should probably put it in OpenShift secrets.

2024-11-11 07:53 UTC, petrberan commented on src/main/java/org/jboss/set/jira/JiraService.java
> +public class JiraService {
https://github.com/jboss-set/build-trigger/issues/69

2024-11-11 08:20 UTC, petrberan commented on src/main/java/org/jboss/set/jira/JiraService.java
> +                    "cc [~eleandro]/[~dkreling]\n\n";
What exactly? Two Jira usernames?

2024-11-11 08:25 UTC, petrberan commented on src/main/java/org/jboss/set/jira/JiraService.java
> +                fields.put("description", "This is an automated issue created by Build Trigger\n\n" +
Lots of questions:

> Are we sure we want to be able to create the issue without assignee?
Yes, this is a fallback for a case when JIRA fails to return the username. That way we still have a log of Build Trigger being used.

> Also how is the reporter of the issue set?
The `jiraKey` contains API key to the JIRA. 

> Who is it now?
Right now it's me :) As I don't want to wait for CIAM any longer

> Is the issue created in dev mode?
Depends if you provided the `jiraKey`. I believe we should be able to test creating the issue even in dev mode. But you got me thinking that maybe we shouldn't file JBEAP issue, but JIRAPLAY issue instead. This would require changing properties

2024-11-11 09:11 UTC, khermano commented on src/main/java/org/jboss/set/jira/JiraService.java
> +    private String authorizationHeader = "Bearer " + jiraKey;
It looks like it will not work: https://quarkus.io/guides/config-reference#inject.
But you can use PostConstruct annotation and that should resolve the issue.

2024-11-11 09:23 UTC, khermano commented on src/main/java/org/jboss/set/jira/JiraService.java
> +                fields.put("description", "This is an automated issue created by Build Trigger\n\n" +
So the reporter is assigned based on who owns the jira-key, correct?

And about creating the issue in dev mode: I was using jira-key from the OpenShift for testing in dev mode, but I did not see any log regarding this issue being or being not created, not even an error was thrown. So I don't know if it was created but I think not because I did not find any JBEAP issue like that.

2024-11-11 10:04 UTC, khermano commented on src/main/java/org/jboss/set/jira/JiraService.java
> +                fields.put("description", "This is an automated issue created by Build Trigger\n\n" +
Update: There was an error thrown:
`2024-11-08 11:50:54,861 ERROR [org.jbo.set.jir.JiraService] (executor-thread-1) Failed to send issue to Jira: Received: 'Bad Request, status code 400' when invoking REST Client method: 'org.jboss.set.client.JiraRestClient#sendIssue'
2024-11-08 11:50:54,862 ERROR [org.jbo.set.jir.JiraService] (executor-thread-1) [org.jboss.resteasy.reactive.client.impl.RestClientRequestContext.unwrapException(RestClientRequestContext.java:205), org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.handleException(AbstractResteasyReactiveContext.java:329), org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:175), org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:324), io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:270), io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:252), io.vertx.core.impl.ContextInternal.lambda$runOnContext$0(ContextInternal.java:50), io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:173), io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:166), io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:566), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:994), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.base/java.lang.Thread.run(Thread.java:1583)]`

2024-11-11 15:46 UTC, khermano approved these changes
Thanks @petrberan

2024-11-12 06:51 UTC, merged

2024-11-12 06:51 UTC, petrberan commented
Sorry @xjusko that I didn't wait for your approve, I need to test this final iteration